version: '3.8'
services:
  postgres:
    image: postgres:14
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-blog}
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: